[client]
toolbarMode = "minimal"
showErrorDetails = "stacktrace"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#126c83"
backgroundColor = "#fbfcfd"
secondaryBackgroundColor = "#eef2f6"
textColor = "#17202a"
font = "sans-serif"
baseRadius = "0.45rem"
showWidgetBorder = true
